@prefix deps:  <http://ontologi.es/doap-deps#> .

<http://purl.org/NET/cpan-uri/dist/Sub-Lazy/project>
	deps:runtime-requirement         [ deps:on "Attribute::Handlers"^^deps:CpanId ];
	deps:runtime-requirement         [ deps:on "Data::Thunk"^^deps:CpanId ];
	deps:test-requirement            [ deps:on "Test::More 0.61"^^deps:CpanId ].

